buildCommand: npm install && npm run build
startCommand: npm run server
envVars:
  - key: NODE_ENV
    value: production
  - key: APP_URL
    value: https://buyfrommoss.vercel.app
  - key: SENDGRID_API_KEY
    sync: false
  - key: VITE_GOOGLE_CLIENT_ID
    sync: false
  - key: PORT
    value: 4000
